### ISSUE TITLE
Compile error (using sbt)

### ISSUE THREAD

**Issue by misja-alma** [siddhartha-gadgil/jzy3d-example#1]
Hi, your example project seemed very useful so I cloned it and ran sbt clean compile, however it fails with this error:

`sbt.internal.inc.InvalidComponent: The compiler bridge sources org.scala-sbt:compiler-bridge_2.13:1.1.0:compile could not be retrieved.`

**Comment by siddhartha-gadgil** [comment]
Thanks, should be fixed now (in 45bd4558c1fc6d). I had updated the scala version but not the sbt version (as I use mill). 

You can use `sbt example/run` to plot an example.

**Comment by misja-alma** [comment]
Thanks! It works now.
